Разметка главной страницы
htmlacademy-htmlcss/1959447-gllacy-33 pull request #2
Opened 2022-01-25 09:00 UTC by ElenaMihailova

Выполнена разметка главной страницы

2022-01-26 09:04 UTC, ElenaMihailova commented
Разметка страницы каталога

2022-01-26 11:04 UTC, nikopol-fw requested changes

2022-01-26 11:04 UTC, nikopol-fw commented on Readme.md
> +* Студент: [Elena    Mihailova](https://up.htmlacademy.ru/htmlcss/33/user/1959447).
Зачем тут появились пробелы?)

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +          <a class="navigation_logo" href="#">
На главной странице следует убрать атрибут `href` у ссылки логотипа. Не будем делать переход страницы на саму себя. Тег a без href более не будет являться ссылкой, но удобство для программирования шаблона, оставив тег, мы сохраним.

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +          </ul>
1. В nav следует добавлять только конкретные страницы сайта, обычно доступные всем, не конкретному пользователю. Таким образом ссылка не телефон сюда не подходит точно. Вход и корзина конкретного пользователя — нечего им делать в навигации. Поисковики иногда могут ссылки в навигации добавить в набор быстрых ссылок для сайта
![image](https://user-images.githubusercontent.com/22588831/151148502-9fcc4aa3-15aa-4d15-9220-b3afff9e2a11.png)
Рекомендую второй список из nav убрать.
2. Формат ссылки на телефон некорректен, должно быть так: `tel:${number}`
https://developer.mozilla.org/ru/docs/Web/HTML/Element/A#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8_%D1%81_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%BE%D0%BC_%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%B0
3. Логотипу в навигации скорее всего тоже не место. В первую очередь логотип несет другую роль, ссылка в нем это скорее побочный эффект пользовательского опыта. Вот если бы была ссылка "Главная", ее можно в навигацию. Но подобная ссылка является, скорее, архаизмом.

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +                        <button name="button" type="button">Заказать</button>
По слайдеру
1. Почему ol? В слайдере есть какая-то нумерация?
2. Мороженки, что мы видем как бы в слайде — это не 3 мороженных внутри одного слайда. Это 3 слайда, в каждом по 1-ой мороженки. Пока постарайся не обращать внимание на визуальное их отображение. Далее этот вопрос решим на css (мороженки видны, например, на первом слайде из других слайдов)
Таким образом 1 слайд — 1-но мороженное. Кнопки влево/вправо — общие для всего слайдера, они не являются частью слайда, потому должны быть в единственном экземпляре, как, например, кнопки `slider_pagination`. Их место в разметке где-то по соседству. Вопрос их расположения визуально решается также с помощью css.
3. Почему "Заказать" — это кнопка type button. Получается минимум возможностей без js. Лучше ссылки.

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +              </div>
Список ul будет лучше и удобнее

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +              </div>
Также списком. Можно еще и на ссылки заменить. Отображение разных слайдов можно сделать без использования js переходами по ссылкам

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +                      <button class="button_cart" name="button"> <span class="visually-hidden">Корзина</span></button>
1. Явно следует указывать type у кнопок. У всех.
2. Если type не указан, то кнопки по умолчанию submit, но такой тип не имеет смысла без form. Здесь напрашивается ссылка "Добавить в корзину"
3. Конечно иконки не следует делать с помощью img. Комментарий можно удалить

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +                    <img class="advantages_pic" src="Img/ice.png" alt="Мороженое">
img - это контент. А контент это изображение чего-то конкретного. А alt - описание этого конкретного. "Мороженое" — очень скудное описание. На изображении мы не видим ничего конкретного, иконка. Отсюда делаю вывод, что img тут не очень уместен.
Рекомендую убрать. В будущем или css или svg решит задачу

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +          </article>
1. Однозначно все должно быть ссылкой для удобства. Без ссылки блок не имеет смысла, так как не решает никаких задач. Ведь он похож на превью. Перейди и узнай подробности — типичный пользовательский кейс.
2. А вот картинка напрашивается как img, скорее всего блок теоретически формируется в админке разрабатываемого сайта, где пишется заголовок, текст и добавляется картинка превью к статье.
3. Почему h4. Число у заголовка h отображает не визуальное оформление текста (эта задача решается с помощью css), а уровень вложенности контента. Так как тут article (самостоятельный, завершенный контент), то или h2 или h1 (выбирается реже, чтобы не конкурировать с h1 для названия страницы)

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +              <h3 class="visually-hidden">Подписка на новостную рассылку</h3>
h3? Тоже самое. Оценивая уровень твоих section, вижу, что везде следует ставить h1
main (h1)
main > section (h2)
main > section >section (h3)
main > section > ul > li (h3)
main > section > section > ul > li (h4>
main > section > ul > li (h3) > section (h4) + section (h4) > ul > li (h5)
Надеюсь примеры написал понятно

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +              <h4 class="contacts_titel">Адрес главного офиса и офлайн-магазина:</h4>
В общем везде проработать `h`-заголовки

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +              <img class="img_contacts_back" src="Img/Contacts.png" alt="Три рожка с мороженым">
А вот тут непонятно как картинка соотносится с адресом, к чему этот контент? Я бы делал на css. Не вижу тут смысловой нагрузки. Но это не строго

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +            </div>
Может списком?

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +            </div>
В ТЗ, где макеты в figm'е есть пояснения, какие именно части должны быть ссылкой, следует поправить.
Также рекомендую использовать атрибуты `target="_blank"`, чтобы ссылки на сторонний ресурс открывались в отдельном окне, и не закрывали наш сайт

2022-01-26 11:04 UTC, nikopol-fw commented on index.html
> +                    <li class="documents_item">Экологические стандарты</li>
Тут напрашиваются ссылки внутри. Иначе смысл от этих кусочков текста?

2022-01-26 19:43 UTC, ElenaMihailova reviewed
Внесены правки

2022-01-26 20:11 UTC, ElenaMihailova reviewed
Разметка страницы каталога

2022-01-27 10:24 UTC, nikopol-fw commented on catalog.html
> +    </section>
Как-то неожиданно закончилась секция. Наверно, закрывающий тег должен быть значительно ниже?

2022-01-27 10:24 UTC, nikopol-fw commented on catalog.html
> +          <option value="popular">По популярности</option>
Не хватает `label`. Вижу, что есть `aria-label`, но в макете явно видно слово "Сортировка:". Его как-то нужно будет вывести. `label` для select также применим.

Ну или legend, если ты интерпретируешь все эти надписи как заголовки групп полей.

2022-01-27 10:24 UTC, nikopol-fw commented on catalog.html
> +          </li>
Чтобы type radio работал, как единый элемент (переключение/выбор работал), то следует задавать единый name для всех input, которые ты хочешь связать. Для определения в данных, какой был выбран, input'ам проставляется атрибут value

input radio не связанный с другим, не имеет смысла, так как сам элемент предполагает выбор одного из нескольких

2022-01-27 10:24 UTC, nikopol-fw approved these changes

2022-01-27 10:26 UTC, merged